//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO.WebUI.Resources.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DetailsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STO.WebUI.Resources.View.DetailsRes", typeof(DetailsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить автомобиль.
        /// </summary>
        public static string AddCar {
            get {
                return ResourceManager.GetString("AddCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее состояние.
        /// </summary>
        public static string AvgState {
            get {
                return ResourceManager.GetString("AvgState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тормоза.
        /// </summary>
        public static string Brake {
            get {
                return ResourceManager.GetString("Brake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кузов.
        /// </summary>
        public static string CarCase {
            get {
                return ResourceManager.GetString("CarCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список машин.
        /// </summary>
        public static string CarList {
            get {
                return ResourceManager.GetString("CarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер автомобиля.
        /// </summary>
        public static string CarNumber {
            get {
                return ResourceManager.GetString("CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип автомобиля.
        /// </summary>
        public static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата добавления.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двигатель.
        /// </summary>
        public static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные услуги:.
        /// </summary>
        public static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поручни.
        /// </summary>
        public static string Handrail {
            get {
                return ResourceManager.GetString("Handrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гидравлика.
        /// </summary>
        public static string Hydraulics {
            get {
                return ResourceManager.GetString("Hydraulics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сиденья.
        /// </summary>
        public static string Seat {
            get {
                return ResourceManager.GetString("Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замена обшивки сидения.
        /// </summary>
        public static string SkinReplacement {
            get {
                return ResourceManager.GetString("SkinReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К оплате всего {0} денег.
        /// </summary>
        public static string TotalPricePageResult {
            get {
                return ResourceManager.GetString("TotalPricePageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ходовая.
        /// </summary>
        public static string Undercarriage {
            get {
                return ResourceManager.GetString("Undercarriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение должно бить в диапазоне от 0 до 100.
        /// </summary>
        public static string ValRang0100Fld {
            get {
                return ResourceManager.GetString("ValRang0100Fld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательное для заполнения.
        /// </summary>
        public static string ValRequiredFld {
            get {
                return ResourceManager.GetString("ValRequiredFld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер автомобиля должен состоять с 8 символов.
        /// </summary>
        public static string ValStrLengthFld {
            get {
                return ResourceManager.GetString("ValStrLengthFld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колеса.
        /// </summary>
        public static string Wheel {
            get {
                return ResourceManager.GetString("Wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Балансировка колес.
        /// </summary>
        public static string WheelBalancing {
            get {
                return ResourceManager.GetString("WheelBalancing", resourceCulture);
            }
        }
    }
}
